[package]
name = "ergo"
version = "0.1.0"
authors = ["Daniel Imfeld <daniel@imfeld.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-cors = "0.5.4"
actix-identity = "0.3.1"
actix-session = "0.4.1"
actix-web = "3.3.2"
anyhow = "1.0.38"
async-stream = "0.3.0"
async-trait = "0.1.48"
chrono = { version = "0.4", features = ["serde"] }
cookie = "0.14.0"
deadpool = "0.7.0"
derivative = "2.2.0"
dotenv = "0.15.0"
either = "1.6.1"
futures = "0.3.13"
fxhash = "0.2.1"
hashicorp_vault = "2.0.1"
jsonschema = "0.6.1"
jsonwebtoken = "7.2.0"
libreauth = "0.14.0"
log = "0.4.14"
pbkdf2 = "0.7.4"
quick-js = "0.4.1"
reqwest = "0.11.2"
serde = { version="1.0.124", features=["derive"] }
serde_json = "1.0.64"
smallvec = { version="1.6.1", features=["serde"] }
sqlx = { version="0.5.1", features=["postgres", "json", "uuid", "chrono", "time", "runtime-tokio-rustls"] }
thiserror = "1.0.24"
tokio = { version="1.4.0", features=["full", "test-util"] }
tracing = "0.1.25"
tracing-actix-web = "0.2"
tracing-bunyan-formatter = "0.1.7"
tracing-futures = "0.2.5"
tracing-log = "0.1.2"
tracing-subscriber = { version = "0.2.17", features=["registry", "env-filter"] }
uuid = { version="0.8.2", features=["serde", "v4"] }

[dev-dependencies]
assert_matches = "1.5.0"
libc = "0.2.90"
wiremock = "0.5.1"
