[package]
name = "ergo"
version = "0.1.0"
authors = ["Daniel Imfeld <daniel@imfeld.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.0.0-beta.4"
anyhow = "1.0.38"
async-stream = "0.3.0"
async-trait = "0.1.48"
chrono = { version = "0.4", features = ["serde"] }
deadpool = "0.7.0"
derivative = "2.2.0"
dotenv = "0.15.0"
either = "1.6.1"
futures = "0.3.13"
fxhash = "0.2.1"
hashicorp_vault = "2.0.1"
log = "0.4.14"
reqwest = "0.11.2"
serde = { version="1.0.124", features=["derive"] }
serde_json = "1.0.64"
sqlx = { version="0.5.1", features=["postgres", "json", "chrono", "time", "runtime-tokio-rustls"] }
thiserror = "1.0.24"
tokio = { version="1.4.0", features=["full", "test-util"] }
tracing = "0.1.25"
tracing-actix-web = "0.3.0-beta.2"
tracing-bunyan-formatter = "0.1.7"
tracing-futures = "0.2.5"
tracing-log = "0.1.2"
tracing-subscriber = { version = "0.2.17", features=["registry", "env-filter"] }

[dev-dependencies]
assert_matches = "1.5.0"
libc = "0.2.90"
wiremock = "0.5.1"
