
[workspace]
members = [
  "api",
  "auth",
  "database",
  "graceful_shutdown",
  "js",
  "notifications",
  "queues",
  "tasks",
  "test",
  "wasm"
]
resolver = "2"

# [profile.release]
# lto = true

