[package]
name = "ergo"
version = "0.1.0"
authors = ["Daniel Imfeld <daniel@imfeld.dev>"]
edition = "2018"

[lib]
name = "ergo"

[[bin]]
name = "aio-server"
path = "src/bin/aio-server.rs"

[[bin]]
name = "erq"
path = "src/bin/erq.rs"

[features]
test-redis = []
test-all = ["test-redis"]

[dependencies]
actix-cors = "0.5.4"
actix-identity = "0.3.1"
actix-session = "0.4.1"
actix-web = "3.3.2"
anyhow = "1.0.38"
async-channel = "1.6.1"
async-stream = "0.3.0"
async-trait = "0.1.48"
blocking = "1.0.2"
chrono = { version = "0.4", features = ["serde"] }
config = "0.11.0"
cookie = "0.14.0"
crossbeam = "0.8.0"
deadpool = "0.7.0"
deadpool-redis = "0.7.1"
derivative = "2.2.0"
dotenv = "0.15.0"
either = "1.6.1"
futures = "0.3.13"
fxhash = "0.2.1"
hashicorp_vault = "2.0.1"
itertools = "0.10.0"
jsonschema = "0.6.1"
jsonwebtoken = "7.2.0"
libreauth = "0.14.0"
log = "0.4.14"
pbkdf2 = "0.7.4"
quick-js = "0.4.1"
rand = "0.8.3"
redis = { version="0.20.0", features=["tokio-comp"] }
reqwest = "0.11.2"
serde = { version="1.0.124", features=["derive"] }
serde_json = "1.0.64"
serde_millis = "0.1.1"
smallvec = { version="1.6.1", features=["serde"] }
sqlx = { version="0.5.1", features=["postgres", "json", "uuid", "chrono", "time", "runtime-tokio-rustls"] }
structopt = "0.3.21"
thiserror = "1.0.24"
tokio = { version="1.4.0", features=["full", "test-util"] }
tracing = "0.1.25"
tracing-actix-web = "0.2"
tracing-bunyan-formatter = "0.1.7"
tracing-futures = "0.2.5"
tracing-log = "0.1.2"
tracing-subscriber = { version = "0.2.17", features=["registry", "env-filter"] }
uuid = { version="0.8.2", features=["serde", "v4"] }

[dev-dependencies]
assert_matches = "1.5.0"
libc = "0.2.90"
wiremock = "0.5.1"
