
[workspace]
members = [
  "api",
  "auth",
  "database",
  "graceful_shutdown",
  "js",
  "notifications",
  "queues",
  "tasks",
  "test",
  "wasm"
]

# [profile.release]
# lto = true

[patch.crates-io]
sqlx = { git="https://github.com/dimfeld/sqlx" }
