[package]
name = "ergo-tasks"
version = "0.2.0"
authors = ["Daniel Imfeld <daniel@imfeld.dev>"]
edition = "2018"

[lib]
path = "lib.rs"

[dependencies]
anyhow = "1.0.42"
async-trait = "0.1.50"
backoff = { version = "0.3.0", features = ["tokio"] }
chrono = { version = "0.4.19", features = ["serde"] }
ergo-database = { version = "0.1.0", path="../database" }
ergo-graceful-shutdown = { version = "0.1.0", path="../graceful_shutdown" }
ergo-js = { version = "0.0.0", path="../js" }
ergo-notifications = { version = "0.2.0", path="../notifications" }
ergo-queues = { version = "0.2.0", path="../queues" }
ergo-task-types = { version = "0.2.0", path="../task_types" }
futures = "0.3.15"
fxhash = "0.2.1"
handlebars = "4.0.0"
itertools = "0.10.0"
jsonschema = "0.9.0"
lazy_static = "1.4.0"
rand = "0.8.3"
rand_core = "0.6.2"
reqwest = { version="0.11.4", features=["rustls-tls"] }
schemars = { git="https://github.com/dimfeld/schemars", branch="sqlx-json", features=["smallvec", "uuid", "chrono", "preserve_order", "sqlx"] }
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"
serde_millis = "0.1.1"
smallvec = { version = "1.6.1", features = ["serde", "union"] }
sqlx = { version = "0.5.5", features = ["postgres", "json", "uuid", "chrono", "time", "runtime-tokio-rustls"] }
thiserror = "1.0.25"
tokio = { version = "1.9.0", features = ["full", "test-util"] }
tracing = "0.1.26"
uuid = { version = "0.8.2", features = ["serde", "v4"] }

[dev-dependencies]
assert_matches = "1.5.0"
once_cell = "1.8.0"
# syn = { version="1.0.73", features=["full"] }
# quote = "1.0.9"
wiremock = "0.5.3"

[build-dependencies]
ergo-js = { version = "0.0.0", path="../js" }
