BEGIN;

CREATE TYPE notify_service AS ENUM (
  'email',
  'discord_incoming_webhook',
  'slack_incoming_webhook'
);

CREATE TABLE notify_endpoints (
  notify_endpoint_id bigint primary key generated by default as identity,
  org_id uuid not null references orgs,
  service notify_service not null,
  destination text not null
);

CREATE TYPE notify_event AS ENUM (
  'input_arrived',
  'input_processed',
  'action_started',
  'action_success',
  'action_error'
);

CREATE TABLE notify_listeners (
  notify_listener_id bigint primary key generated by default as identity,
  notify_endpoint_id bigint not null references notify_endpoints ,
  object_id bigint references object_ids,
  event notify_event not null
);

COMMENT ON COLUMN notify_listeners.object_id is 'The object to listen on, or NULL for all applicable objects';

CREATE INDEX notify_listeners_event_object_id ON notify_listeners(event, object_id);

COMMIT;
