BEGIN;

DO $$BEGIN
  CREATE ROLE ergo_admin INHERIT;
  EXCEPTION WHEN duplicate_object THEN NULL;
END; $$;

CREATE ROLE ergo_user INHERIT;
CREATE ROLE ergo_web NOINHERIT IN ROLE ergo_user;
CREATE ROLE ergo_backend NOINHERIT IN ROLE ergo_user;
CREATE ROLE ergo_enqueuer NOINHERIT IN ROLE ergo_user;

ALTER DEFAULT PRIVILEGES REVOKE ALL ON TABLES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES REVOKE ALL ON FUNCTIONS FROM PUBLIC;
ALTER DEFAULT PRIVILEGES REVOKE CREATE ON SCHEMAS FROM PUBLIC;
ALTER DEFAULT PRIVILEGES GRANT ALL ON SCHEMAS TO ergo_admin;
ALTER DEFAULT PRIVILEGES GRANT ALL ON TABLES TO ergo_admin;
ALTER DEFAULT PRIVILEGES GRANT ALL ON FUNCTIONS TO ergo_admin;

COMMIT;
