BEGIN;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE user_entity_ids (
  user_entity_id uuid primary key default uuid_generate_v4()
);

-- The Global user entity id, for ownership purposes
INSERT INTO user_entity_ids (user_entity_id) VALUES (uuid_nil());

CREATE TABLE object_ids (
  object_id bigint primary key generated by default as identity
    (start with 2)
);

-- The Global object id, for permissions
INSERT INTO object_ids (object_id) VALUES (1);

CREATE TYPE permission AS ENUM (
  'trigger_event'
);

CREATE TABLE user_entity_permissions (
  user_entity_id uuid not null references user_entity_ids (user_entity_id),
  permission_type permission not null,
  permissioned_object bigint not null references object_ids(object_id),

  primary key(user_entity_id, permission_type, permissioned_object)
);

COMMENT ON TABLE user_entity_permissions IS 'Permissions for users and roles';

CREATE TABLE orgs (
  org_id uuid not null primary key references user_entity_ids(user_entity_id),
  name text not null,
  active boolean default true,
  created timestamptz not null default now()
);

CREATE TABLE users (
  user_id uuid not null primary key references user_entity_ids(user_entity_id),
  active_org_id uuid not null references orgs(org_id),
  name text not null,
  email text unique not null,
  password text,
  active boolean default true,
  created timestamptz not null default now()
);

CREATE UNIQUE INDEX ON users (email);

CREATE TABLE roles (
  role_id uuid not null primary key references user_entity_ids(user_entity_id),
  org_id uuid not null references orgs (org_id),
  name text not null,
  created timestamptz not null default now()
);

CREATE TABLE user_roles (
  user_id uuid not null references users,
  role_id uuid not null references roles,
  org_id uuid not null references orgs,
  primary key (user_id, org_id, role_id)
);

CREATE TABLE api_keys (
  api_key_id uuid primary key references user_entity_ids(user_entity_id),
  org_id uuid not null references orgs,
  user_id uuid references users,
  description text,

  active boolean default true,
  expires timestamptz,
  created timestamptz not null default now()
);

CREATE INDEX ON api_keys (org_id);

COMMENT ON TABLE api_keys IS 'API keys for users and organizations';

COMMIT;
