[package]
name = "ergo-graceful-shutdown"
version = "0.1.0"
authors = ["Daniel Imfeld <daniel@imfeld.dev>"]
edition = "2018"

[lib]
path = "lib.rs"

[dependencies]
tokio = { version = "1.9.0", features = ["full", "test-util"] }

[dev-dependencies]
assert_matches = "1.5.0"
libc = "0.2.95"
