[package]
name = "ergo-wasm"
version = "0.1.0"
edition = "2018"

[lib]
name = "ergo_wasm"
path = "lib.rs"
crate-type = ["cdylib"]

[dependencies]
json5 = "0.3.0"
ergo-task-types = { version = "0.2.0", path="../task_types" }
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"
wasm-bindgen = "0.2.76"

