#!/bin/bash
set -euo pipefail

ENV_FILE=$(dirname $(realpath $0))/../.env
if [ -f "$ENV_FILE" ]; then
  source $ENV_FILE
fi

psql -d ${DATABASE_URL} -1 <<EOF
ALTER ROLE ${DATABASE_ROLE_WEB_USERNAME:-ergo_web}
  LOGIN PASSWORD '${DATABASE_ROLE_WEB_PASSWORD}';

ALTER ROLE ${DATABASE_ROLE_BACKEND_USERNAME:-ergo_backend}
  LOGIN PASSWORD '${DATABASE_ROLE_BACKEND_PASSWORD}';

ALTER ROLE ${DATABASE_ROLE_ENQUEUER_USERNAME:-ergo_enqueuer}
  LOGIN PASSWORD '${DATABASE_ROLE_ENQUEUER_PASSWORD}';
EOF

